import React, { useRef } from 'react'
import { Parallax, ParallaxLayer, IParallax } from '@react-spring/parallax'
import Head from 'next/head'
import { FaCaretLeft } from 'react-icons/fa'
import ThemeToggle from '../theme/ThemeToggle'
import Link from 'next/link'

const url = (name, wrap = false) =>
  `${wrap ? 'url(' : ''}https://awv3node-homepage.surge.sh/build/assets/${name}.svg${wrap ? ')' : ''}`

export default function More() {
  const parallax = useRef(null)
  return (
    <div className='bg-purple dark:bg-gray h-screen'>
      <Head>
        <title>Shoury Sharma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ width: '100%', height: '100%' }}>
          <Parallax ref={parallax} pages={3}>
            <div className='flex justify-between py-4 px-4'>
              <Link href='/'>
                <FaCaretLeft className='text-white text-4xl' />
              </Link>
              <ThemeToggle />
            </div>
            <ParallaxLayer offset={1} speed={1} />
            <ParallaxLayer offset={2} speed={1} />

            <ParallaxLayer
              offset={0}
              speed={0}
              factor={3}
              style={{
                backgroundImage: url('stars', true),
                backgroundSize: 'cover',
              }}
            />

            <ParallaxLayer offset={1.3} speed={-0.3} style={{ pointerEvents: 'none' }}>
              <img src={url('satellite4')} style={{ width: '15%', marginLeft: '70%' }} />
            </ParallaxLayer>

            <ParallaxLayer offset={1} speed={0.8} style={{ opacity: 0.1 }}>
              <img src={url('cloud')} style={{ display: 'block', width: '20%', marginLeft: '55%' }} />
              <img src={url('cloud')} style={{ display: 'block', width: '10%', marginLeft: '15%' }} />
            </ParallaxLayer>

            <ParallaxLayer offset={1.75} speed={0.5} style={{ opacity: 0.1 }}>
              <img src={url('cloud')} style={{ display: 'block', width: '20%', marginLeft: '70%' }} />
              <img src={url('cloud')} style={{ display: 'block', width: '20%', marginLeft: '40%' }} />
            </ParallaxLayer>

            <ParallaxLayer offset={1} speed={0.2} style={{ opacity: 0.2 }}>
              <img src={url('cloud')} style={{ display: 'block', width: '10%', marginLeft: '10%' }} />
              <img src={url('cloud')} style={{ display: 'block', width: '20%', marginLeft: '75%' }} />
            </ParallaxLayer>

            <ParallaxLayer offset={1.6} speed={-0.1} style={{ opacity: 0.4 }}>
              <img src={url('cloud')} style={{ display: 'block', width: '20%', marginLeft: '60%' }} />
              <img src={url('cloud')} style={{ display: 'block', width: '25%', marginLeft: '30%' }} />
              <img src={url('cloud')} style={{ display: 'block', width: '10%', marginLeft: '80%' }} />
            </ParallaxLayer>

            <ParallaxLayer offset={2.6} speed={0.4} style={{ opacity: 0.6 }}>
              <img src={url('cloud')} style={{ display: 'block', width: '20%', marginLeft: '5%' }} />
              <img src={url('cloud')} style={{ display: 'block', width: '15%', marginLeft: '75%' }} />
            </ParallaxLayer>

            <ParallaxLayer
              offset={2.5}
              speed={-0.4}
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                pointerEvents: 'none',
              }}>
              <img src={url('earth')} style={{ width: '60%' }} />
            </ParallaxLayer>

            <ParallaxLayer
              offset={2}
              speed={-0.3}
              style={{
                backgroundSize: '80%',
                backgroundPosition: 'center',
                backgroundImage: url('clients', true),
              }}
            />

            <ParallaxLayer
              offset={0}
              speed={0.1}
            // onClick={() => parallax.current.scrollTo(1)}
            >
              <div className='flex justify-between py-4 px-4'>
                <Link href='/'>
                  <FaCaretLeft className='text-white text-4xl' />
                </Link>
                <ThemeToggle />
              </div>
              {/* <img src={url('server')} style={{ width: '20%' }} /> */}
            </ParallaxLayer>

            <ParallaxLayer
              offset={1}
              speed={0.1}
              onClick={() => parallax.current.scrollTo(2)}
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}>

              Projects
              {/* <img src={url('bash')} style={{ width: '40%' }} /> */}
            </ParallaxLayer>

            <ParallaxLayer
              offset={2}
              speed={-0}
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
              onClick={() => parallax.current.scrollTo(0)}>
              Links
              {/* <img src={url('clients-main')} style={{ width: '40%' }} /> */}
            </ParallaxLayer>
          </Parallax>
        </div>
      </main >
      <footer>

      </footer>
    </div >
  )
}
